Add jvm-clients.options files for C* 4.0
datastax/cass-config-definitions pull request #49
Opened 2021-02-10 19:09 UTC by emerkle826

This is intended to resolve #48 . For Cassandra 4.0, nodetool expects there to be a `/etc/cassandra/jvm8-clients.options` file, even if it is empty it seems. This PR attempts to add the templates for `jvm-clients.options`, `jvm8-clients.options` and `jvm11-clients.options`.

2021-02-10 20:47 UTC, scottbale requested changes
I'm afraid it may not be as simple to add these definitions as we both would hope. There are unit test failures which I'm still trying to figure out. You can see these yourself by
* git-cloning [cass-config-builder](https://github.com/datastax/cass-config-builder) if you haven't already
* Running this unit test, pointing config-builder at your local copy of `cass-config-definitions`:

```
~/dev/cass-config-builder$ ./gradlew test -Pdefinitions.location=~/dev/cass-config-definitions/resources
```

When I do this I'm seeing three test failures:
```
build-config-test. test-allow-custom-seed-provider
build-config-test. test-build-configs-for-oss-cassandra
definitions-test. test-get-template
```
Each of them have similar error messages:
```
"There is no definition transforms file for jvm-clients.options for version 3.11.6"
```

I wanted to leave early feedback but I'm still trying myself to understand these failures. It may be related to [OPSC-16473](https://datastax.jira.com/browse/OPSC-16473) - evidently support for OSS C* definitions were added hastily last year. I'm hoping not but it may be that these changes may require an accompanying code change in `cass-config-builder`.

One unrelated minor comment: is there some reason you went with folder names containing periods, e.g. `jvm8-clients.options`, rather than `jvm8-clients-options` which seems to be the existing convention? I don't think it hurts, but it caught my eye.

2021-02-10 21:02 UTC, emerkle826 commented
> One unrelated minor comment: is there some reason you went with folder names containing periods, e.g. `jvm8-clients.options`, rather than `jvm8-clients-options` which seems to be the existing convention? I don't think it hurts, but it caught my eye.

Good catch. My eyes apparently are not as good as they used to be.

2021-02-10 21:03 UTC, emerkle826 commented
> ~/dev/cass-config-builder$ ./gradlew test -Pdefinitions.location=~/dev/cass-config-definitions/resources

Thanks for that, I'm still trying to learn the config-builder stuff and I wasn't sure how the two were integrated.

2021-02-10 21:54 UTC, emerkle826 commented
@scottbale thanks again. It seems the folder names using `.` instead of `-` was wrong, and fixing that led me to a few curly brace mismatches that I was able to fix.

2021-02-15 05:21 UTC, jsanda commented
Hi @scottbale 

Thanks for reviewing the PR. I work on the k8ssandra project with Erik. I do not have any prior experience with developing/testing cass-config-builder. When I run tests again master, I get 26 failures. Is that expected? I just want to establish a baseline. 

Here is my output so you can see what failed:

```
$ ./gradlew test -Pdefinitions.location=~/dev/cass-config-definitions/resources

Welcome to Gradle 6.0.1!

Here are the highlights of this release:
 - Substantial improvements in dependency management, including
   - Publishing Gradle Module Metadata in addition to pom.xml
   - Advanced control of transitive versions
   - Support for optional features and dependencies
   - Rules to tweak published metadata
 - Support for Java 13
 - Faster incremental Java and Groovy compilation
 - New Zinc compiler for Scala
 - VS2019 support
 - Support for Gradle Enterprise plugin 3.0

For more details see https://docs.gradle.org/6.0.1/release-notes.html


> Task :test

com.datastax.configbuilder.render-test > test-render-config-package-proxy FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.render-test > test-render-config-default FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.definitions-test > test-consistent-dse-major-version-lists FAILED
    java.lang.AssertionError
        Caused by: java.io.FileNotFoundException

com.datastax.configbuilder.definitions-test > check-all-definitions FAILED
    java.lang.AssertionError
        Caused by: java.io.FileNotFoundException

com.datastax.configbuilder.definitions-test > test-get-template FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.definitions-test > test-default-dse-version-dse-yaml-definition FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.definitions-test > test-get-field-metadata FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.definitions-test > test-get-all-definitions-for-version FAILED
    java.lang.AssertionError
    java.lang.AssertionError

com.datastax.configbuilder.definitions-test > test-dse-6-7-0-yaml FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.definitions-test > test-config-file-valid? FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.render.config-file-renderer-test > test-render-spark-alwayson-sql-conf FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.render.config-file-renderer-test > test-render-dse-env-sh-custom-env-vars FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.render.config-file-renderer-test > test-render-config-file FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.render.config-file-renderer-test > test-render-jvm-options FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-allow-custom-seed-provider FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-unmanage-config-file FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-build-configs-for-oss-cassandra FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-build-configs-file-paths FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-fully-qualify-paths FAILED
    java.lang.AssertionError
    java.lang.AssertionError
    java.lang.AssertionError

com.datastax.configbuilder.build-config-test > test-build-configs-no-enrichment FAILED
    java.lang.AssertionError

com.datastax.configbuilder.build-config-test > test-get-configured-paths FAILED
    java.lang.AssertionError
    java.lang.AssertionError
    java.lang.AssertionError

com.datastax.configbuilder.build-config-test > test-build-configs FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.build-config-test > test-with-defaults FAILED
    java.lang.AssertionError
    java.lang.AssertionError
    java.lang.AssertionError

com.datastax.configbuilder.operator-test > test-make-configs FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder.golden-files-test > diff-against-golden-files FAILED
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

com.datastax.configbuilder-test > test-configbuilder FAILED
    java.lang.AssertionError
    java.lang.AssertionError
        Caused by: clojure.lang.ExceptionInfo

100 tests completed, 26 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/jsanda/Development/datastax/cass-config-builder/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
```

2021-02-15 15:54 UTC, emerkle826 commented
@jsanda I got the same errors when running the test in cass-config-builder without specifying a definitions location. However, once I fixed a few things in this PR, it started to pass. FOr the record, I run this:
```
./gradlew test -Pdefinitions.location=/home/emerkle/workspace/cass-config-definitions/resources
```
where `/home/emerkle/workspace/cass-config-definitions/resources` is checked out to my PR branch here.

2021-02-15 17:40 UTC, jsanda commented
@emerkle826 I get 26 failures when using your branch 🤔 

I am curious to understand what is involved because I need to make additional changes for https://github.com/k8ssandra/k8ssandra/issues/324.

2021-02-16 17:51 UTC, emerkle826 commented
Digging a little further, I realized that `cass-config-builder` actually pulls this stuff in as a git submodule. After cloning `cass-config-builder`, I failed to do this:
```sh
git submodule init
git submodule update
```
After performing those two steps, running `./gradlew test` passes.

Locally, I rebased my definitions branch on the latest master branch here, and now I get 1 test failure that I think is related to the most recent change here: 

https://github.com/datastax/cass-config-definitions/pull/47/files#diff-c6d8afbfcc9d781cfae661a21f04b01962011dccdf1a3a807f1f278ebb2b8bfaR21-R22

The test failure indicates this:

> Found transform for version 5.1.21 in /home/emerkle/workspace/cass-config-builder/cass-config-definitions/resources/jvm-options/dse/jvm-options-dse-transforms.edn but that version isn't present in versions.edn

@jsanda I also noticed that the tests don't seem to pickup changes I make to the definitions each time, so I've tried to do a `./gradlew clean` before each run as well.

2026-02-23 14:51 UTC, closed without merging